version: "3.9"
services:
  worker:
    build: .
    environment:
    VARS:
      SESSION: $SESSION
      TEAM7: $TEAM7
      API_ID_KEY: $API_ID_KEY 
      API_HASH_KEY : $API_HASH_KEY 
      MONGO_DB_URL: $MONGO_DB_URL
      Inspectors: $Inspectors
      Enforcers: $Enforcers
      Team7_logs: $Team7_logs
      Team7_Approved_logs: $Team7_Approved_logs
      GBAN_MSG_LOGS: $GBAN_MSG_LOGS
      BOT_TOKEN: $BOT_TOKEN
      ENV: $ENV
