help_plus = """
Here are BanCodes :- 
√ `{T7x00} - SCAMMER.`
√ `{T7x01} - SPAM ADDING MEMBER.`
√ `{T7x03} - ABUSE SPAM.`
√ `{T7x04} - NSFW SPAMMER.`
√ `{T7x06} - IMPERSONATION.`
√ `{T7x07} - MD/BTC SCAM.`
√ `{T7x08} - ADDING SPAMBOTS.`
√ `{T7x10} - ILLEGAL.`
√ `{T7x11} - PHISHING.`
√ `{T7x12} - FRAUD PROMOTION  [ANY KIND].`
√ `{T7x13} - CYBER THREATENING / CYBER BULLY.`
√ `{T7x14} - CHILD ABUSE.`
√ `{T7x15} - BAN EVASION.`
√ `{T7x16} - SPAMBOT.`
√ `{T7x17} - RAID INITIALIZOR.`
√ `{T7x18} - RAID PARTICIPANT.`
√ `{T7x19} - KRIMINALANT.`
√ `{T7x20} - RAID/SPAM INFLAMMER.`
√ `{RD-00} - RAID // SCAMMER BAN BY SCANNER BOT'S REPORTS.`
"""

__plugin_name__ = "bancodes"
